### ISSUE TITLE
Upgrade to Node.js v20

### ISSUE THREAD

**Issue by eason9487** [woocommerce/grow#108]
## Description

This repo currently uses Node.js v14, which has reached its end-of-life 2023-04-30.

#### JS package `generator-grow`

- [x] Upgrade for dependencies, generators, and tests ([#111](https://github.com/woocommerce/grow/pull/111))
- [x] Update the actions' version in the templates of JS package `generator-grow` ([#129](https://github.com/woocommerce/grow/pull/129))

#### JS package `jsdoc` and `tracking-jsdoc`

- [x] Upgrade for JS package `jsdoc` and `tracking-jsdoc` ([#110](https://github.com/woocommerce/grow/pull/110))

#### Package `github-actions`

- [x] Update docs ([#123](https://github.com/woocommerce/grow/pull/123))
- [x] Adjust the v1 to be deprecated ([#124](https://github.com/woocommerce/grow/pull/124))
- [x] The fundamental setup and related workflows ([#112](https://github.com/woocommerce/grow/pull/112))
- [x] `automerge-released-trunk` action ([#114](https://github.com/woocommerce/grow/pull/114))
- [x] `branch-label` action ([#122](https://github.com/woocommerce/grow/pull/122))
- [x] `coverage-report` action ([#114](https://github.com/woocommerce/grow/pull/114))
- [x] `eslint-annotation` action ([#117](https://github.com/woocommerce/grow/pull/117))
- [x] `get-plugin-releases` action ([#119](https://github.com/woocommerce/grow/pull/119))
- [x] `get-release-notes` action ([#112](https://github.com/woocommerce/grow/pull/112))
- [x] `hook-documentation` action ([#115](https://github.com/woocommerce/grow/pull/115))
- [x] `merge-trunk-develop-pr` action ([#121](https://github.com/woocommerce/grow/pull/121))
- [x] `phpcs-diff` action ([#116](https://github.com/woocommerce/grow/pull/116))
- [x] `prepare-extension-release` action ([#121](https://github.com/woocommerce/grow/pull/121))
- [x] `prepare-mysql` action ([#115](https://github.com/woocommerce/grow/pull/115))
- [x] `prepare-node` action ([#112](https://github.com/woocommerce/grow/pull/112))
- [x] `prepare-php` action ([#114](https://github.com/woocommerce/grow/pull/114))
- [x] `publish-extension-dev-build` action ([#121](https://github.com/woocommerce/grow/pull/121))
- [x] `run-qit-annotate` action ([#115](https://github.com/woocommerce/grow/pull/115))
- [x] `run-qit-extension` action ([#120](https://github.com/woocommerce/grow/pull/120))
- [x] `stylelint-annotation` action ([#117](https://github.com/woocommerce/grow/pull/117))
- [x] `update-version-tags` action ([#112](https://github.com/woocommerce/grow/pull/112))

#### The root dependencies, setup, and related workflows of this repo

- [x] The root dependencies and setup ([#113](https://github.com/woocommerce/grow/pull/113))
- [x] The related workflows ([#135](https://github.com/woocommerce/grow/pull/135))

**Comment by eason9487** [comment]
Closing this issue as the upgrade has been completed.
